apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: vedtak-arkivering
  namespace: flex
  labels:
    team: flex
  annotations:
    dcat.data.nav.no/title: "flex.vedtak-arkivering"
    dcat.data.nav.no/description: "Midlertidig topic for arkivering av uarkiverte vedtak"
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: flex
      application: spinnsyn-arkivering
      access: read