apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: spinnsyn-db
            diskAutoresize: true
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
    inbound:
      rules:
        - application: spinnsyn-backend-proxy

  envFrom:
    - secret: spinnsyn-backend-serviceuser
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SPINNSYN_FRONTEND_URL
      value: "https://www-q1.dev.nav.no/syk/sykepenger"
    - name: OIDC_WELLKNOWN_URI
      value: "https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1"
    - name: LOGINSERVICE_CLIENTID
      value: "0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5"
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
