apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        diskAutoresize: true
        databases:
          - name: spinnsyn-db
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: kafka-schema-registry.nais-q.adeo.no
        - host: syfo-tilgangskontroll.dev-fss-pub.nais.io
        - host: navtestb2c.b2clogin.com
    inbound:
      rules:
        - application: flex-gateway
        - application: flex-intern-gateway
        - application: spinnsyn-frontend-arkivering
        - application: spinnsyn-arkivering
        - application: spinnsyn-frontend-interne
        - application: spinnsyn-frontend
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
  envFrom:
    - secret: spinnsyn-backend-serviceuser
    - configmap: loginservice-idporten
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "default,testdatareset"
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SPINNSYN_FRONTEND_URL
      value: "https://www-gcp.dev.nav.no/syk/sykepenger"
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.dev-fss-pub.nais.io
    - name: SYFOTILGANGSKONTROLL_AAD_CLIENT_ID
      value: dev-fss.teamsykefravr.syfo-tilgangskontroll
    - name: SPINNSYN_FRONTEND_CLIENT_ID
      value: dev-gcp:flex:spinnsyn-frontend
    - name: SPINNSYN_FRONTEND_TOKENX_IDP
      value: https://oidc-ver2.difi.no/idporten-oidc-provider/
