db_tier: db-f1-micro
db_type: POSTGRES_11
kafkaPool: nav-dev
replicas_min: 2
replicas_max: 2
cpu: 300m
memory: 600Mi
flex-openapi-docs-ui: true
external-host:
  - pdl-api.dev-fss-pub.nais.io
env:
  PDL_BASE_URL: https://pdl-api.dev-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: dev-fss.pdl.pdl-api
  SPRING_PROFILES_ACTIVE: default, testdata
  ISTILGANGSKONTROLL_URL: http://istilgangskontroll.teamsykefravr
  ISTILGANGSKONTROLL_AAD_CLIENT_ID: dev-gcp.teamsykefravr.istilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: dev-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
