db_tier: db-f1-micro
kafkaPool: nav-dev
replicas_min: 2
replicas_max: 2
cpu: 300m
memory: 600Mi
env:
  SPRING_PROFILES_ACTIVE: default, testdata
  SYFOTILGANGSKONTROLL_URL: http://syfo-tilgangskontroll.teamsykefravr
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: dev-gcp.teamsykefravr.syfo-tilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: dev-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  TOKENX_IDP_IDPORTEN: https://oidc-ver2.difi.no/idporten-oidc-provider/
