kafkaPool: nav-dev
replicas_min: 2
replicas_max: 2
syfotilgangskontrollExternalHost: syfo-tilgangskontroll.dev-fss-pub.nais.io
b2cloginExternalHost: navtestb2c.b2clogin.com
env:
  SPRING_PROFILES_ACTIVE: default, testdata
  SYFOTILGANGSKONTROLL_URL: https://syfo-tilgangskontroll.dev-fss-pub.nais.io
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: dev-fss.teamsykefravr.syfo-tilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: dev-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: dev-gcp:flex:ditt-sykefravaer
  TOKENX_IDP_IDPORTEN: https://oidc-ver2.difi.no/idporten-oidc-provider/
