apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  tokenx:
    enabled: true
  kafka:
    pool: {{kafkaPool}}
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: spinnsyn-db
            users:
              - name: bigquery-dataprodukt
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  accessPolicy:
    outbound:
      rules:
        - application: syfo-tilgangskontroll
          namespace: teamsykefravr
    inbound:
      rules:
        - application: spinnsyn-frontend-arkivering
        - application: spinnsyn-frontend-interne
        - application: spinnsyn-frontend
        - application: ditt-sykefravaer
  azure:
    application:
      enabled: true
      allowAllUsers: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
