db_tier: db-custom-2-7680
db_highAvailability: true
db_pointInTimeRecovery: true
db_type: POSTGRES_14
kafkaPool: nav-prod
replicas_min: 2
replicas_max: 3
cpu: 100m
memory: 1000Mi
external-host:
  - pdl-api.prod-fss-pub.nais.io
env:
  PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io
  PDL_API_AAD_CLIENT_ID: prod-fss.pdl.pdl-api
  ISTILGANGSKONTROLL_URL: http://istilgangskontroll.teamsykefravr
  ISTILGANGSKONTROLL_AAD_CLIENT_ID: prod-gcp.teamsykefravr.istilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: prod-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
