kafkaPool: nav-prod
replicas_min: 2
replicas_max: 3
syfotilgangskontrollExternalHost: syfo-tilgangskontroll.prod-fss-pub.nais.io
b2cloginExternalHost: navnob2c.b2clogin.com
env:
  SYFOTILGANGSKONTROLL_URL: https://syfo-tilgangskontroll.prod-fss-pub.nais.io
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: prod-fss.teamsykefravr.syfo-tilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: prod-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
  TOKENX_IDP_IDPORTEN: https://oidc.difi.no/idporten-oidc-provider/
