db_tier: db-custom-1-3840
kafkaPool: nav-prod
replicas_min: 2
replicas_max: 3
cpu: 600m
memory: 800Mi
env:
  SYFOTILGANGSKONTROLL_URL: http://syfo-tilgangskontroll.teamsykefravr
  SYFOTILGANGSKONTROLL_AAD_CLIENT_ID: prod-gcp.teamsykefravr.syfo-tilgangskontroll
  SPINNSYN_FRONTEND_CLIENT_ID: prod-gcp:flex:spinnsyn-frontend
  DITT_SYKEFRAVAER_CLIENT_ID: prod-gcp:flex:ditt-sykefravaer
  TOKENX_IDP_IDPORTEN: https://oidc.difi.no/idporten-oidc-provider/
