CREATE TABLE organisasjon
(
    ID           VARCHAR(36) DEFAULT uuid_generate_v4() PRIMARY KEY,
    ORGNUMMER    VARCHAR(15)              NOT NULL UNIQUE,
    NAVN         VARCHAR(255)             NOT NULL,
    OPPRETTET    TIMESTAMP WITH TIME ZONE NOT NULL,
    OPPDATERT    TIMESTAMP WITH TIME ZONE NOT NULL,
    OPPDATERT_AV VARCHAR(36)              NOT NULL
);
