ALTER TABLE vedtak ALTER COLUMN opprettet TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE vedtak ALTER COLUMN lest TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE vedtak ALTER COLUMN varslet TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE vedtak ALTER COLUMN revarslet TYPE TIMESTAMP WITH TIME ZONE;
